homeassistant:
  name: Home
  latitude: XX.XXXXX
  longitude: XX.XXXXX
  temperature_unit: F
  time_zone: America/New_York
  customize: !include customize.yaml

zone:
  name: Work
  latitude: XX.XXXXX
  longitude: XX.XXXXX
  radius: 250
  icon: mdi:worker

mqtt:
  broker: XXX.XXX.XXX.XXX
  port: 1883
  client_id: home-assistant-1
  keepalive: 60
  username: USERNAME
  password: PASSWORD


http:
  api_password: XXXXXXXXXXXXXXX
  ssl_certificate: '/etc/letsencrypt/live/HAname.duckdns.org/fullchain.pem'
  ssl_key: '/etc/letsencrypt/live/HAname.duckdns.org/privkey.pem'

ifttt:
  key: XXXXXXXXXXXXXXXXXXXX


####################################################
#                                                  #
#                     Includes             #
#                                                  #
####################################################

###  Devices  ###
alexa: !include devices/alexa.yaml
camera: !include devices/cameras.yaml
device_tracker: !include devices/device_trackers.yaml
light: !include devices/lights.yaml
media_player: !include devices/media_players.yaml
sensor: !include devices/sensors.yaml
switch: !include devices/switches.yaml
alarm_control_panel: !include alarm_control_panel.yaml
automation: !include automation.yaml
group: !include groups.yaml
#input_boolean: !include input_boolean.yaml
input_select: !include input_select.yaml
notify: !include notify.yaml
scene: !include scenes.yaml
script: !include scripts.yaml
shell_command: !include shell_commands.yaml

####################################################
#                                                  #
#                     Enables             #
#                                                  #
####################################################
logger:
frontend:
history:
discovery:
sun:
conversation:
logbook:









 

















