- platform: mjpeg
  mjpeg_url: http://XXX.XXX.XXX.XXX:10010/videostream.cgi
  name: Front Door
  username: USERNAME
  password: PASSWORD
##CAMERA 2
- platform: mjpeg
  mjpeg_url: http://XXX.XXX.XXX.XXX:10001/videostream.cgi
  name: Porch
  username: USERNAME
  password: PASSWORD 
