####MEDIA PLAYERS####
- platform: kodi
  url: http://192.168.1.125:8080/jsonrpc
  name: osmc
#media_player 2:
#  platform: kodi
#  url: http://192.168.1.141:8080/jsonrpc
#  name: KODI CMStormtrooper
- platform: universal
  name: Living Room Media
  children:
    - media_player.osmc
    - media_player.chromecast
  commands:
    turn_on:
       service: switch.turn_on
       data: switch.tv_power