- platform: command_line
  switches:
    bedroom_fan:
      oncmd: 'sudo python /var/opt/homeassistant/HA/rf/rf.py a'
      offcmd: 'sudo python /var/opt/homeassistant/HA/rf/rf.py b'
    bedroom_lamp:
     oncmd: 'sudo python /var/opt/homeassistant/HA/rf/rf.py c'
     offcmd: 'sudo python /var/opt/homeassistant/HA/rf/rf.py d'
    livingroom_wall_outlet:
      oncmd: 'sudo python /var/opt/homeassistant/HA/rf/rf.py e'
      offcmd: 'sudo python /var/opt/homeassistant/HA/rf/rf.py f'
    livingroom_desk_outlet:
      oncmd: 'sudo python /var/opt/homeassistant/HA/rf/rf.py g'
      offcmd: 'sudo python /var/opt/homeassistant/HA/rf/rf.py h'
    kitchen_outlet:
      oncmd: 'sudo python /var/opt/homeassistant/HA/rf/rf.py i'
      offcmd: 'sudo python /var/opt/homeassistant/HA/rf/rf.py j'
    bedroom_blinds:
      oncmd: 'sudo python /var/opt/homeassistant/HA/rf/rf.py k'
      offcmd: 'sudo python /var/opt/homeassistant/HA/rf/rf.py l'
    kitchen_blinds:
      oncmd: 'sudo python /var/opt/homeassistant/HA/rf/rf.py m'
      offcmd: 'sudo python /var/opt/homeassistant/HA/rf/rf.py n'
    livingroom_blinds:
      oncmd: 'sudo python /var/opt/homeassistant/HA/rf/rf.py o'
      offcmd: 'sudo python /var/opt/homeassistant/HA/rf/rf.py p'
    pc_power:
      oncmd: 'sudo etherwake -b MAC:ADDRESS:XX:XX:XX:XX'
      offcmd: 'sudo net rpc shutdown -f -t 0 -I XXX.XXX.XXX.XXX -U  windowsusername%windowspassword'
    hyperion:
      oncmd: '/var/opt/homeassistant/HA/hyperion/hyperionon.sh'
      offcmd: '/var/opt/homeassistant/HA/hyperion/hyperionoff.sh'
    tv_power:
      oncmd:  'echo "on 0" | cec-client -s RPI'
      offcmd:  'echo "standby 0" | cec-client -s RPI'
    avr_power:
      oncmd:  'echo "on 5" | cec-client -s RPI'
      offcmd:  'echo "standby 5" | cec-client -s RPI'